version: "3.8"

services:
  authentication-service:
    build:
      context: ./AUTH-SERVICE
      dockerfile: Dockerfile
    container_name: mcp_db
    environment:
      SERVER_PORT: 9898
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: mcp_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "9898:9898"
    depends_on:
      - mysql

  backend-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      SERVER_PORT: 8080
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: mcp_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "8081:8081"
    depends_on:
      - mysql

  api-gateway:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8989:8989"
    depends_on:
      - authentication-service
      - backend-service

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  mysql:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leave_management_system
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  eureka-server:
    build:
      context: ./eurekaServer
      dockerfile: Dockerfile
    container_name: eurekaServer
    ports:
      - "8761:8761"

  cloud-config-server:
    build:
      context: ./CloudConfigServer
      dockerfile: Dockerfile
    container_name: CloudConfigServer
    ports:
      - "9196:9196"

volumes:
  mysql_data:












